[package]
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Pure Rust implementation of XML-RPC"
license = "MIT"
name = "xml-rpc"
readme = "README.md"
repository = "https://github.com/adnanademovic/xml-rpc-rs"
version = "0.0.12"

[dependencies]
base64 = "0.13.0"
error-chain = "0.12.4"
reqwest = { version = "0.11.2", features = ["blocking"] }
lazy_static = "1.0.0"
regex = "1.4.5"
serde = "1.0.11"
serde-xml-rs = "0.4.1"
serde_bytes = "0.11.5"
serde_derive = "1.0.11"
xml-rs = "0.8.3"
rouille = "3.0.0"
