[package]
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Pure Rust implementation of XML-RPC"
license = "MIT"
name = "xml-rpc"
readme = "README.md"
repository = "https://github.com/adnanademovic/xml-rpc-rs"
version = "0.1.0"
[[bin]]
name = "echo"
path = "examples/echo.rs"

[dependencies]
base64 = "0.6.0"
error-chain = "0.10.0"
futures = "0.1.14"
serde = "1.0.11"
serde-xml-rs = "0.2.1"
serde_derive = "1.0.11"
tokio-core = "0.1.9"

[dependencies.hyper]
default-features = false
version = "0.11.2"

[lib]
name = "xml_rpc"
path = "src/lib.rs"
