[package]
name = "hyper10"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
repository = "https://github.com/adnanademovic/xml-rpc-rs"
license = "MIT"
description = "Enables depending on hyper 0.10 and other hyper versions in the same crate."

[dependencies]
hyper = "0.10"
